# Generated by Django 4.2 on 2026-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
